version: "3.3"

services:
    PaymentDb:
        image: mariadb:10.5-focal
        container_name: PaymentCtnr
        ports:
            - ${MYSQL_PORT}:3306
        labels:
            - payment-db
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-u$MYSQL_ROOT_PASSWORD",
                    "-p$MYSQL_PASSWORD",
                    "-h",
                    "127.0.0.1",
                ]
            interval: 10s
            timeout: 20s
            retries: 5
