<?php

namespace yii\payment;

use linslin\yii2\curl\Curl;
use yii\base\Component;
use yii\base\InvalidConfigException;
use yii\payment\caching\Cache;
use yii\payment\caching\CachingInterface;
use yii\payment\enum\Status;
use yii\payment\exceptions\RatePullException;
use yii\payment\provider\RazorPay;

class Gateway extends Component
{
    public array $providers = [];


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (!$this->providers) {
            throw new InvalidConfigException('Property "providers" is mandatory for payment component.');
        }

    }

    public function processPayment(string $gatewayName): Response
    {
        /** var $selectedProvider */
        $selectedProvider = \Yii::createObject($this->providers[$gatewayName]);
        return $selectedProvider->process();
    }

}